version: "3.9"

services:
  rie-php-cli:
    build:
      context: ./docker/php-cli
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - rie-network

  rie-nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8888:80"
    tty: true
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - rie-network

  rie-php-fpm:
    build:
      context: ./docker/php-fpm
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - rie-network

  rie-mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./rie-mariadbdata:/var/lib/mysql

networks:
  rie-network:

volumes:
  rie-mariadbdata:
      driver: local
