version: '3'

services:
  rieapp:
    image: laravel-rie-server
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8888:80"
    networks:
      - rienetwork
    depends_on:
      - riemariadb

  riemariadb:
    image: mariadb:10
    ports:
      - "33067:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "riemariadbdata:/var/lib/mysql"
    networks:
      - rienetwork

networks:
  rienetwork:
    driver: bridge

volumes:
  riemariadbdata:
    driver: local
